openapi: 3.0.1
info:
  title: Transaction API
  description: API pour la gestion des transactions utilisateur (Phase 2).
  version: 1.0.0

paths:
  /transactions:
    get:
      summary: Récupère toutes les transactions du mois en cours pour un utilisateur
      description: Récupère la liste des transactions d'un utilisateur pour le mois courant.
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: integer
          description: ID de l'utilisateur pour récupérer ses transactions.
      responses:
        '200':
          description: Transactions récupérées avec succès.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '404':
          description: Utilisateur ou transactions non trouvées.
        '500':
          description: Erreur interne du serveur.

  /transactions/{transactionId}:
    get:
      summary: Récupère les détails d'une transaction spécifique
      description: Récupère toutes les informations sur une transaction spécifique.
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: integer
          description: ID de la transaction.
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '404':
          description: Transaction non trouvée.
        '500':
          description: Erreur interne du serveur.

    patch:
      summary: Modifie des informations d'une transaction
      description: Met à jour certains détails d'une transaction (montant, description, catégorie) sans modifier la transaction en elle-même.
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: integer
          description: ID de la transaction.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionUpdate'
      responses:
        '200':
          description: Informations de la transaction mises à jour avec succès.
        '400':
          description: Requête invalide.
        '404':
          description: Transaction non trouvée.
        '500':
          description: Erreur interne du serveur.

components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: integer
          description: ID unique de la transaction.
        userId:
          type: integer
          description: ID de l'utilisateur associé.
        amount:
          type: number
          format: float
          description: Montant de la transaction.
        description:
          type: string
          description: Description de la transaction.
        date:
          type: string
          format: date
          description: Date de la transaction.
        category:
          type: string
          description: Catégorie de la transaction.

    TransactionInput:
      type: object
      properties:
        amount:
          type: number
          format: float
          description: Montant de la transaction.
        description:
          type: string
          description: Description de la transaction.
        date:
          type: string
          format: date
          description: Date de la transaction.
        category:
          type: string
          description: Catégorie de la transaction.

    TransactionUpdate:
      type: object
      properties:
        amount:
          type: number
          format: float
          description: Montant de la transaction à mettre à jour.
        description:
          type: string
          description: Nouvelle description de la transaction.
        category:
          type: string
          description: Nouvelle catégorie de la transaction.
